project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "5293 demo-pancake"
  author:
    - Yichao Wang (yw4324)
  repo-url: https://github.com/yichaowanggg/demo-pancake
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


